/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import menu.trans;

/**
 *
 * @author User
 */
public class ajoutetransaction extends javax.swing.JFrame {

    /**
     * Creates new form ajoutetransaction
     */
    public ajoutetransaction() {
        initComponents();
    }
public java.sql.Connection getConnection()
    {
        java.sql.Connection con = null;
        
        try{
            con = DriverManager.getConnection("jdbc:MySQL://localhost:3306/matel","root","");
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        return con;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        brandname = new javax.swing.JTextField();
        tradate = new com.toedter.calendar.JDateChooser();
        type = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        currentdate = new javax.swing.JTextField();
        traid = new javax.swing.JTextField();
        groupname = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        pinid = new javax.swing.JTextField();
        accountmobile = new javax.swing.JTextField();
        accountname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        access = new javax.swing.JTextField();
        msisdn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(226, 234, 244));

        jPanel1.setBackground(new java.awt.Color(226, 234, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(226, 234, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Veuillez remplir les formulaires pour ajoutrer une transaction");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 590, 30));

        brandname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandnameActionPerformed(evt);
            }
        });
        jPanel3.add(brandname, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 391, 207, 31));

        tradate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(tradate, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 139, 207, 31));
        jPanel3.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 201, 207, 34));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 567, 488, 54));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("type");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 207, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("tradate");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 143, 109, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("status");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("amount");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 339, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("brandname");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 395, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voir gestion");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, -5, 310, 50));

        currentdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentdateActionPerformed(evt);
            }
        });
        jPanel3.add(currentdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 139, 185, 31));
        jPanel3.add(traid, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 201, 185, 34));
        jPanel3.add(groupname, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 331, 185, 39));
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 265, 207, 33));

        pinid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinidActionPerformed(evt);
            }
        });
        jPanel3.add(pinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 266, 185, 38));
        jPanel3.add(accountmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 495, 185, 35));
        jPanel3.add(accountname, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 389, 185, 35));
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 443, 185, 33));
        jPanel3.add(access, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 443, 207, 33));
        jPanel3.add(msisdn, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 495, 207, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("currentdate\t");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 139, 99, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("traid");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 207, 99, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("accountname");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 388, 99, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("groupname");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 330, 99, 39));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("pinid");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 265, 99, 38));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("username");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 442, 99, 33));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("accountmobile");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 494, -1, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("access");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 442, 59, 33));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("msisdn\t");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 501, 59, -1));
        jPanel3.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 334, 207, 33));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Bureau\\PFE\\12.jpg")); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1200, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brandnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        trans d;
     d = new trans();
        d.setVisible(true);
       
        d.pack();
        d.setLocationRelativeTo(null); 
        this.dispose();    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pinidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String currentdate1, traid1, pinid1, groupname1,accountname1,username1,accountmobile1,tradate1,type1,status1,
amount1,brandname1,access1,msisdn1,query;
      
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/matel";
        SUser = "root";
        SPass = "";
         Date dateHeureDate = tradate.getDate();
        try {
            java.sql.Connection con = getConnection();
            java.sql.Statement st = con.createStatement();
            if("".equals(currentdate.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre currentdate", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(traid.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre traid ", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(pinid .getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre votre pinid ", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }     if("".equals( groupname.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre groupname ", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(accountname.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre accountname ", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(username.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre votre username", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }     if("".equals(accountmobile.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir accountmobile", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(type.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre votre type", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }     if("".equals(status.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir status", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(amount.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir amount", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(brandname.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir votre brandname", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }     if("".equals(access.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir access", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(msisdn.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir msisdn	", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(formatDate(dateHeureDate))){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir tradate", "Error",
                        JOptionPane.ERROR_MESSAGE);
          }
else {
            currentdate1 = currentdate.getText(); 
            traid1   = traid.getText();
             pinid1 =pinid.getText();
             groupname1 = groupname.getText();
            accountname1 =accountname.getText();
	username1 = username.getText();
	accountmobile1 = accountmobile.getText();

 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tradate1 = sdf.format(dateHeureDate);
type1 =type.getText();
status1 =status.getText();
amount1 = amount.getText();
brandname1 = brandname.getText();
access1 = access.getText();
msisdn1 = msisdn.getText();

            
           query = "INSERT INTO tra(currentdate, traid, pinid, groupname, accountname, username, accountmobile, msisdn, access, brandname, amount, status, tradate, type) " +
                        "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                try (PreparedStatement stmt = con.prepareStatement(query)) {
                    stmt.setString(1, currentdate1);
                    stmt.setString(2, traid1);
                    stmt.setString(3, pinid1);
                    stmt.setString(4, groupname1);
                    stmt.setString(5, accountname1);
                    stmt.setString(6, username1);
                    stmt.setString(7, accountmobile1);
                    stmt.setString(8, msisdn1);
                    stmt.setString(9, access1);
                    stmt.setString(10, brandname1);
                    stmt.setString(11, amount1);
                    stmt.setString(12, status1);
                    stmt.setString(13, tradate1);
                    stmt.setString(14, type1);

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "La transaction est enregistrée avec succès !");
                     trans b = new trans();
                
                b.setVisible(true);
                b.pack();
                b.setLocationRelativeTo(null); 
                this.dispose();
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erreur lors de l'enregistrement : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erreur de connexion : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    

 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void currentdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutetransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutetransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutetransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutetransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutetransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField access;
    private javax.swing.JTextField accountmobile;
    private javax.swing.JTextField accountname;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField brandname;
    private javax.swing.JTextField currentdate;
    private javax.swing.JTextField groupname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField msisdn;
    private javax.swing.JTextField pinid;
    private javax.swing.JTextField status;
    private com.toedter.calendar.JDateChooser tradate;
    private javax.swing.JTextField traid;
    private javax.swing.JTextField type;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

   private String formatDate(Date dateHeureDate ) {
    if (dateHeureDate == null) {
        return ""; // Ou une autre valeur par défaut que vous jugez appropriée
    }
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    return sdf.format(dateHeureDate);
}

}
