/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class Ajoute extends javax.swing.JFrame {

    /**
     * Creates new form Ajoute
     */
    public Ajoute() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomV1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NomV2 = new javax.swing.JTextField();
        Numero = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        Solde = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enregistrer = new javax.swing.JButton();
        DateHeure = new com.toedter.calendar.JDateChooser();
        DateCreation = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        COMBO = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(226, 234, 244));
        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(1399, 887));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(226, 234, 244));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date et Heure");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 245, 223, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date de création");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 232, 203, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOM REVENDEUR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, -1, 44));

        NomV1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(NomV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 235, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom revendeur ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 208, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 395, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 133, 36));

        NomV2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        NomV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomV2ActionPerformed(evt);
            }
        });
        jPanel1.add(NomV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 263, 40));

        Numero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 288, 40));

        Type.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        jPanel1.add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 235, 40));

        Solde.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        Solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldeActionPerformed(evt);
            }
        });
        jPanel1.add(Solde, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 263, 36));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SOLDE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 150, -1));

        enregistrer.setBackground(new java.awt.Color(0, 153, 153));
        enregistrer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documents\\NetBeansProjects\\matel\\src\\icone\\enre.png")); // NOI18N
        enregistrer.setText("ENREGISTRER");
        enregistrer.setBorder(null);
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        jPanel1.add(enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 235, 40));

        DateHeure.setBackground(new java.awt.Color(204, 204, 204));
        DateHeure.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        DateHeure.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        DateHeure.setMaxSelectableDate(new java.util.Date(253370768502000L));
        jPanel1.add(DateHeure, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 263, 40));

        DateCreation.setBackground(new java.awt.Color(204, 204, 204));
        DateCreation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        DateCreation.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(DateCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 268, 40));

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Veuillez remplir les formulaires");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 130, 387, 56));

        COMBO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        COMBO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "groupe1", "groupe2", "groupe3", "groupe4" }));
        jPanel1.add(COMBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 288, 39));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GROUPE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 126, 34));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("M:\\ICONE\\mattel.png")); // NOI18N
        jLabel9.setText("Mattel");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Voir gestion ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 820, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1387, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Bureau\\PFE\\12.jpg")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 1190, 610));

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        String date1 ,date2 , Nom1,Nom2,Numero1,Type1,Solde1,COMBO1, query;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/matel";
        SUser = "root";
        SPass = "";

    Date dateHeureDate = DateHeure.getDate();
     Date datecre = DateCreation.getDate();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
             java.sql.Statement st = con.createStatement();
            if("".equals(NomV1.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir le premiere nom de revendeur", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(NomV2.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir le deuxieme nom de revendeur", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(Numero.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir le numero de revendeur", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else if("".equals(Type.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir  le type", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(Solde.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "veuillez saisir le solde", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } 
else {
  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                date1 = sdf.format(dateHeureDate);
	   date2 = sdf.format(datecre);
	COMBO1 = (String) COMBO.getSelectedItem();
            Nom1= NomV1.getText(); 
	Solde1=Solde.getText();
            Nom2    = NomV2.getText();
            Numero1= Numero.getText();
            Type1 = Type.getText();
            
          
          
           query = "INSERT INTO donnees(DATE_HEURE, DATE_CREATION, NOM_V1, NOM_V2, NUMERO, GROUPE, TYPE,SOLDE) " +
                        "VALUES(?, ?, ?, ?, ?, ?, ?, ?)";

                try (PreparedStatement stmt = con.prepareStatement(query)) {
                    stmt.setString(1, date1);
                    stmt.setString(2, date2);
                    stmt.setString(3, Nom1);
                    stmt.setString(4, Nom2);
                    stmt.setString(5,Numero1);
                    stmt.setString(6, COMBO1);
                    stmt.setString(7, Type1);
                    stmt.setString(8, Solde1);
                    

                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Le revendeur  est enregistré avec succès !");
                     index b = new index();
                
                b.setVisible(true);
                b.pack();
                b.setLocationRelativeTo(null); 
                this.dispose();
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erreur lors de l'enregistrement : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erreur de connexion : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ajoute.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enregistrerActionPerformed

    private void SoldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoldeActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    private void NomV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomV2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          index a = new index ();
        a.setVisible(true);
       
        a.pack();
        a.setLocationRelativeTo(null); 
        this.dispose();   
    }//GEN-LAST:event_jButton1ActionPerformed

    
   private String formatDate(Date date) {
    if (date == null) {
        return ""; // Ou une autre valeur par défaut que vous jugez appropriée
    }
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    return sdf.format(date);
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajoute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COMBO;
    private com.toedter.calendar.JDateChooser DateCreation;
    private com.toedter.calendar.JDateChooser DateHeure;
    private javax.swing.JTextField NomV1;
    private javax.swing.JTextField NomV2;
    private javax.swing.JTextField Numero;
    private javax.swing.JTextField Solde;
    private javax.swing.JTextField Type;
    private javax.swing.JButton enregistrer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
